apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-flame-hub-server-core"
  labels:
    app: "{{ .Release.Name }}-flame-hub-server-core"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-flame-hub-server-core"
  template:
    metadata:
      name: "{{ .Release.Name }}-flame-hub-server-core"
      labels:
        app: "{{ .Release.Name }}-flame-hub-server-core"
    spec:
      restartPolicy: Always
      initContainers:
          -   name: wait-for-db
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-mysql-primary 3306; do echo "Waiting for db..."; sleep 5; done'
              ]
          -   name: wait-for-redis
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-redis-master 6379; do echo "Waiting for redis..."; sleep 5; done'
              ]
          -   name: wait-for-rabbitmq
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-rabbitmq 5672; do echo "Waiting for rabbitmq..."; sleep 5; done'
              ]
          -   name: wait-for-vault
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-vault 8200; do echo "Waiting for vault..."; sleep 5; done'
              ]
          -   name: wait-for-authup
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-authup-server-core 3000; do echo "Waiting for authup..."; sleep 5; done'
              ]
      containers:
        - name: "{{ .Release.Name }}-flame-hub-server-core"
          image: "ghcr.io/privateaim/hub:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
              -   name: REDIS_CONNECTION_STRING
                  value: "redis://default:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master"
              -   name: VAULT_CONNECTION_STRING
                  value: "start123@http://{{ .Release.Name }}-vault:8200/v1/"
              -   name: RABBITMQ_CONNECTION_STRING
                  value: "amqp://root:start123@{{ .Release.Name }}-rabbitmq"
              -   name: AUTHUP_URL
                  value: "http://{{ .Release.Name }}-authup-server-core:3000/"
              -   name: SKIP_PROJECT_APPROVAL
                  value: "true"
              -   name: SKIP_ANALYSIS_APPROVAL
                  value: "true"
              -   name: DB_TYPE
                  value: "mysql"
              -   name: DB_HOST
                  value: "{{ .Release.Name }}-mysql-primary"
              -   name: DB_USERNAME
                  value: "root"
              -   name: DB_PASSWORD
                  value: "start123"
              -   name: DB_DATABASE
                  value: "core"
          resources:
              requests:
                  memory: "512Mi"
              limits:
                  memory: "2048Mi"
          readinessProbe:
              httpGet:
                  path: "/"
                  port: 3000
              initialDelaySeconds: 60
              periodSeconds: 5
              timeoutSeconds: 10
          livenessProbe:
              httpGet:
                  path: "/"
                  port: 3000
              failureThreshold: 3
              periodSeconds: 60
              initialDelaySeconds: 90


