{{- if or .Values.global.node.ingress.enabled .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-node-ui-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    component: node-ui-service
    version: {{ .Chart.AppVersion }}
    deployment-id:  {{ .Release.Name }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: &host {{ regexReplaceAll "^https?://(.*)" (include "ui.ingress.hostname" .) "${1}" }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-node-ui-service
                port:
                  number: 3000
  {{- with .Values.ingress.tlsSecretName }}
  tls:
    - hosts: [*host]
      secretName: {{ . }}
  {{- end }}
{{- end }}
