apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-ui-deployment
spec:
  selector:
    matchLabels:
      component: node-ui-service
      version: {{ .Chart.AppVersion }}
      deployment-id:  {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: node-ui-service
        version: {{ .Chart.AppVersion }}
        deployment-id:  {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: node-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: ui
          env:
            - name: NODE_ENV
              value: {{ .Values.env | default "production" | quote }}
            - name: NUXT_PUBLIC_BASE_URL
              value: {{ include "ui.ingress.hostname" . }}
            - name: NUXT_PUBLIC_HUB_ADAPTER_URL
              value: {{ include "ui.adapter.endpoint" . }}
            - name: NUXT_PUBLIC_ORIGIN
              value: {{ printf "%s/flame/api/auth" (include "ui.ingress.hostname" .) }}
            - name: NUXT_PUBLIC_KEYCLOAK_BASE_URL
              value: {{ include "ui.keycloak.endpoint" . }}
            - name: NUXT_KEYCLOAK_CLIENT_ID
              value: {{ .Values.idp.clientId | default "node-ui" | quote }}
            {{ if contains "localhost" (include "ui.keycloak.endpoint" .) }}
            - name: NUXT_K8S_KEYCLOAK_ENDPOINT
              value: {{ include "ui.keycloak.service.endpoint" . }}
            {{ end }}
            - name: NUXT_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ui.keycloak.secretName" . }}
                  key: {{ include "ui.keycloak.secretKey" . }}
            - name: NUXT_AUTH_SECRET
              value: {{ randAlphaNum 32 | b64enc }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
