global:
    imagePullPolicy: "Always"

    redis:
        password: "start123"

    hub:
        hostname: "localhost"

ingress:
    enabled: true

## services

vault:
    server:
        enabled: true
        dev:
            enabled: true
            devRootToken: start123

rabbitmq:
    nameOverride: "hub-rabbitmq"
    auth:
        username: "root"
        password: "start123"

redis:
    nameOverride: "hub-redis"
    auth:
        enabled: true

minio:
    nameOverride: "hub-minio"
    auth:
        rootUser: "admin"
        rootPassword: "start123"

mysql:
    nameOverride: "hub-mysql"
    image:
        pullPolicy: "Always"
    auth:
        rootPassword: "start123"
        replicationPassword: "start123"
    secondary:
        persistence:
            enabled: true
            size: 8Gi
        replicaCount: 2
    primary:
        persistence:
            enabled: true
            size: 8Gi
    architecture: "replication"
