{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-flame-hub-client-ui
spec:
    rules:
        - host: {{ .Values.ingress.hostname }}
          http:
              paths:
                  - path: {{ .Values.ingress.path }}
                    pathType: {{ .Values.ingress.pathType }}
                    backend:
                        service:
                            name: {{ .Release.Name }}-flame-hub-client-ui
                            port:
                                number: 3000
{{- end }}
