apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-hub-server-messenger
    labels:
        app: {{ .Release.Name }}-hub-server-messenger
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Release.Name }}-hub-server-messenger
    template:
        metadata:
            name: {{ .Release.Name }}-hub-server-messenger
            labels:
                app: {{ .Release.Name }}-hub-server-messenger
        spec:
            restartPolicy: Always
            initContainers:
                -   name: wait-for-redis
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-hub-redis-master 6379; do echo "Waiting for redis..."; sleep 5; done'
                    ]
                -   name: wait-for-vault
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-vault 8200; do echo "Waiting for vault..."; sleep 5; done'
                    ]
                -   name: wait-for-authup
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-authup-server-core 3000; do echo "Waiting for authup..."; sleep 5; done'
                    ]
            containers:
                -   name: "{{ .Release.Name }}-hub-server-messenger"
                    image: "ghcr.io/privateaim/hub:latest"
                    args: ["messenger", "start"]
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 3000
                            protocol: TCP
                    env:
                        -   name: REDIS_CONNECTION_STRING
                            value: "redis://default:{{ .Values.global.redis.password }}@{{ .Release.Name }}-hub-redis-master"
                        -   name: VAULT_CONNECTION_STRING
                            value: "start123@http://{{ .Release.Name }}-vault:8200/v1/"
                        -   name: AUTHUP_URL
                            value: "http://{{ .Release.Name }}-authup-server-core:3000/"
                    resources:
                        requests:
                            memory: "512Mi"
                        limits:
                            memory: "2048Mi"
                    readinessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        initialDelaySeconds: 60
                        periodSeconds: 5
                        timeoutSeconds: 10
                    livenessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        periodSeconds: 10
                        timeoutSeconds: 10
