apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Name }}-hub-server-messenger"
spec:
    selector:
        app: "{{ .Release.Name }}-hub-server-messenger"
    ports:
        -   protocol: TCP
            port: 3000
            targetPort: 3000

