{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-hub-sub-paths
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
    rules:
        - host: {{ .Values.global.hub.hostname }}
          http:
              paths:
                  - path: /core(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-hub-server-core
                            port:
                                number: 3000
                  - path: /messenger(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-hub-server-messenger
                            port:
                                number: 3000
                  - path: /storage(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-hub-server-storage
                            port:
                                number: 3000
                  - path: /auth(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-authup-server-core
                            port:
                                number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-hub-root-path
spec:
    rules:
        - host: {{ .Values.global.hub.hostname }}
          http:
              paths:
                  - path: /
                    pathType: "Prefix"
                    backend:
                        service:
                            name: {{ .Release.Name }}-hub-client-ui
                            port:
                                number: 3000
{{- end }}
