apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-message-broker
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: flame
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: flame
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: flame
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-node-message-broker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: AUTH_JWKS_URL
              value: {{ required "A valid JWKS URL for Keycloak is required." (include "broker.keycloak.endpoint" .) }}
            - name: PERSISTENCE_HOSTNAME
              value: "{{ .Release.Name}}-node-message-broker-db"
            - name: PERSISTENCE_PORT
              value: "27017"
            - name: PERSISTENCE_DATABASE_NAME
              value: "message-broker"
            - name: HUB_BASE_URL
              value: {{ required "A valid HUB API base URL is required." (include "broker.hub.coreApi" .) | default "https://api.privateaim.net/" | quote}}
            - name: HUB_AUTH_BASE_URL
              value: {{ required "A valid HUB Auth base URL is required." (include "broker.hub.authApi" .) | default "https://auth.privateaim.net/" | quote }}
            - name: HUB_MESSENGER_BASE_URL
              value: {{ required "A valid HUB Messenger base URL is required." (include "broker.hub.messengerApi" .) | default "https://messenger.privateaim.net/" | quote }}              
            - name: HUB_AUTH_ROBOT_ID
              value: {{ required "A robot ID for the Hub is required." (include "broker.hub.robotUser" .) | quote }}
            - name: HUB_AUTH_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-node-message-broker-hub-auth
                  key: robot-secret
            # DO NOT USE THIS IN PRODUCTION!!! This is just for internal testing purposes.
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
