apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-node-message-broker-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: flame
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  serviceName: {{ .Release.Name }}-node-message-broker-db
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: flame
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  replicas: {{ .Values.db.replicaCount }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: flame
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- with .Values.db.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-node-message-broker-db
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "message-broker"
            - name: TZ
              value: {{ .Values.common.timezone | default "Europe/Berlin" | quote }}
            {{- with .Values.db.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.db.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.db.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /data/db
            {{- with .Values.db.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- toYaml .Values.db.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.db.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.db.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.db.tolerations | nindent 8 }}
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          {{- toYaml .Values.db.persistence.accessModes | nindent 10 }}
        {{- with .Values.db.persistence.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.db.persistence.size }}
