apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hub-adapter-deployment
spec:
  selector:
    matchLabels:
      component: hub-adapter-service
      version: {{ .Chart.AppVersion }}
      deployment-id:  {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: hub-adapter-service
        version: {{ .Chart.AppVersion }}
        deployment-id:  {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api-gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: healthcp
          env:
            - name: API_ROOT_PATH
              value: {{ (include "adapter.root.path" .) | default "" }}
            - name: API_CLIENT_ID
              value: {{ .Values.idp.clientId | default "hub-adapter" | quote }}
            - name: API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "adapter.keycloak.secretName" . }}
                  key: {{ include "adapter.keycloak.secretKey" . }}
            - name: IDP_URL
              value: {{ include "adapter.keycloak.endpoint" . }}
            - name: IDP_REALM
              value: {{ .Values.idp.realm | default "flame" | quote }}  # To be replaced
            - name: RESULTS_SERVICE_URL
              value: {{ include "adapter.results.endpoint" . }}
            - name: PODORC_SERVICE_URL
              value: {{ include "adapter.po.endpoint" . }}
            - name: KONG_ADMIN_SERVICE_URL
              value: {{ include "adapter.kong.endpoint" . }}
            - name: HUB_SERVICE_URL
              value: {{ ( include "adapter.hub.coreApi" .) | default "https://core.privateaim.dev" | quote }}
            - name: HUB_AUTH_SERVICE_URL
              value: {{ ( include "adapter.hub.authApi" .) | default "https://auth.privateaim.dev" | quote }}
            - name: HUB_ROBOT_USER
              value: {{ required "A robot ID for the Hub is required." (include "adapter.hub.robotUser" .) | quote }}  # To be properly filled in
            - name: HUB_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "adapter.hub.secretName" . }}
                  key: "robotSecret"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
